Add Via porting and Stacked Acrylic Case
mattdibi/yampad pull request #16
Opened 2021-11-09 01:40 UTC by TahuTech

hello, i love this yampad, i took the initiative to contribute to developing the case and also firmware.
i just add via porting for ez remapping for yampad, and add file stacked acrylic case.

2021-11-13 09:54 UTC, mattdibi requested changes
Hi @TahuTech 

thanks for your contribution. The stacked acrylic case looks awesome!

A note about the case files: I noticed you shared a `.cdr` file which is [proprietary](https://i.redd.it/7ozal346p6kz.png) and can be only opened through CorelDRAW. Could you share a few alternative formats for easier customization? (`.dxf` comes to mind but anything more open will do).

2021-11-13 10:02 UTC, mattdibi commented on README.md
> +
Add a link to the gallery of images.

```suggestion
Acrylic case image gallery [here](https://github.com/mattdibi/yampad/tree/master/img/acrylic_case/).
```

2021-11-13 13:55 UTC, TahuTech commented
okay done convert to .dfx format

2021-11-14 04:52 UTC, TahuTech reviewed
change format case to .dfx

2021-11-14 12:51 UTC, mattdibi approved these changes
LGTM Thanks :)

2021-11-14 12:51 UTC, merged